### ISSUE TITLE
Link is 404 

### ISSUE THREAD

**Issue by marcoscaceres** [GoogleChrome/houdini-samples#8]
http://googlechrome.github.io/houdini-samples/

**Comment by marcoscaceres** [comment]
sorry, to clarify, the link from the front page of this repository.

**Comment by surma** [comment]
Ah yes, didn’t put an `index.html` in root. Will fix that :)

**Comment by mrflix** [comment]
It is broken again 😔 
I'm not familiar with the most recent developments of github pages but back in the days you needed a gh-pages branch to host the repository on github.

**Comment by surma** [comment]
It works for me: http://googlechromelabs.github.io/houdini-samples/

Keep in mind that the repository migrated to GoogleChromeLabs :)

**Comment by mrflix** [comment]
Weird, when I visited the repository for the first time today the description link was still pointing to http://googlechrome.github.io/houdini-samples/. Thanks for your quick response @surma!

As a heads-up: in the [animation-worklet readme]( https://github.com/GoogleChromeLabs/houdini-samples/blob/master/animation-worklet/README.md) there is also a link to the demos that is still pointing to the googlechrome.github.io url.
